{% set name = "plasflow" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 352d5d7cd73672130e32f3f61c3f2ad95aa684d7aebf7668ab3f2594996c338b
  - url: https://github.com/smaegol/PlasFlow/archive/v1.1.tar.gz
    sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    folder: PlasFlow

build:
  number: 0
  skip: True # [not py35 or osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biopython
    - numpy
    - pandas
    - rpy2
    - scikit-learn
    - scipy
    - bioconductor-biostrings
    - tensorflow
test:
  imports:
    - plasflow
  commands:
    - PlasFlow.py --help

about:
  home: https://github.com/smaegol/PlasFlow
  license: GNU General Public v3 or later (GPLv3+)
  license_family: GPL3
  license_file: LICENSE
  summary: PlasFlow - predicting plasmid sequences in metagenomic data

extra:
  identifiers:
    - doi:10.1093/nar/gkx1321
